version: '3.3'

services:
  api:
    network_mode: bridge
    container_name: node-employee-api
    command: npm run dev
    hostname: node-employee-api
    build:
      context: ./app
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    links:        
      - mongo-cubo:mongo-cubo
    expose:
      - 3001
      - 9229
    ports:
      - 3001:3001
      - 9229:9229
    environment:
      LOG_LEVEL: debug
      MONGODB_ENDPOINT: 'mongodb://mongo-cubo:27017/employee'
      PORT: 3001
      SECRET: 'superduppersecret'

  mongo-cubo:
    network_mode: bridge
    container_name: mongo-cubo
    image: "mongo:3.4-jessie"
    hostname: mongo-cubo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
